// Command gendocs writes the generated files: docs/api-coverage.md from the vendored MediaMTX OpenAPI spec and the
// operations table in internal/mtxapi, docs/config.md from the settings in internal/settings, and
// web/src/api/mediamtx-settings.json (every MediaMTX setting for the UI's forms) from the spec and the pinned release's
// reference mediamtx.yml. With -check it writes nothing and fails if the operations table does not cover the spec
// exactly or a file is stale.
//
//	go run ./cmd/gendocs -spec ../spec/mediamtx/openapi.yaml -lock ../spec/mediamtx/openapi.lock -docs ../docs \
//	  -web ../web/src/api -reference <mediamtx.yml> [-check]
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"mtxui/internal/mtxapi"
	"mtxui/internal/settings"
)

func main() {
	specPath := flag.String("spec", "", "vendored OpenAPI spec")
	lockPath := flag.String("lock", "", "spec lock file (for the MediaMTX version)")
	docsDir := flag.String("docs", "", "docs directory")
	webAPI := flag.String("web", "", "web/src/api directory (for mediamtx-settings.json)")
	reference := flag.String("reference", "", "the reference mediamtx.yml of the pinned release")
	check := flag.Bool("check", false, "verify instead of writing")
	flag.Parse()
	if *specPath == "" || *lockPath == "" || *docsDir == "" || *webAPI == "" || *reference == "" {
		flag.Usage()
		os.Exit(2)
	}
	if err := run(*specPath, *lockPath, *docsDir, *webAPI, *reference, *check); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run(specPath, lockPath, docsDir, webAPI, referencePath string, check bool) error {
	specBytes, err := os.ReadFile(specPath)
	if err != nil {
		return err
	}
	spec, err := mtxapi.ParseSpec(specBytes)
	if err != nil {
		return err
	}
	table, err := mtxapi.Operations()
	if err != nil {
		return err
	}
	if problems := mtxapi.Compare(table, spec); len(problems) > 0 {
		return fmt.Errorf("operations.yaml does not match the spec:\n  %s", strings.Join(problems, "\n  "))
	}
	version, err := lockVersion(lockPath)
	if err != nil {
		return err
	}
	reference, err := os.ReadFile(referencePath)
	if err != nil {
		return err
	}
	settingsJSON, err := renderSettings(version, specBytes, reference)
	if err != nil {
		return err
	}
	docs := map[string][]byte{
		filepath.Join(docsDir, "api-coverage.md"):       renderCoverage(version, spec, table),
		filepath.Join(docsDir, "config.md"):             renderConfig(),
		filepath.Join(webAPI, "mediamtx-settings.json"): settingsJSON,
	}
	for path, doc := range docs {
		if !check {
			if err := os.WriteFile(path, doc, 0o644); err != nil { //nolint:gosec // committed, world-readable docs
				return err
			}
			continue
		}
		current, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Equal(current, doc) {
			return fmt.Errorf("%s is stale: run ./dev gen", path)
		}
	}
	return nil
}

func lockVersion(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sc := bufio.NewScanner(bytes.NewReader(b))
	for sc.Scan() {
		if v, ok := strings.CutPrefix(sc.Text(), "version="); ok && v != "" {
			return v, nil
		}
	}
	return "", fmt.Errorf("%s has no version= line", path)
}

func renderCoverage(version string, spec []mtxapi.SpecOperation, table []mtxapi.Operation) []byte {
	byID := map[string]mtxapi.Operation{}
	counts := map[mtxapi.Access]int{}
	for _, op := range table {
		byID[op.ID] = op
		counts[op.Access]++
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- GENERATED by `./dev gen` (sidecar/cmd/gendocs). Edit sidecar/internal/mtxapi/operations.yaml instead. -->\n\n")
	fmt.Fprintf(&b, "# MediaMTX API coverage\n\n")
	fmt.Fprintf(&b, "Every operation of the MediaMTX v%s Control API (`spec/mediamtx/openapi.yaml`, %d operations) and how this project uses it.\n", version, len(spec))
	fmt.Fprintf(&b, "**Access** is the minimum UI role for which the sidecar's API proxy forwards the call: `viewer` < `operator` < `admin`.\n")
	fmt.Fprintf(&b, "`sidecar` operations are called only by the sidecar itself and never proxied for browsers; `unused` ones are never called.\n\n")
	fmt.Fprintf(&b, "| Access | Operations |\n|---|---|\n")
	for _, a := range mtxapi.Accesses {
		fmt.Fprintf(&b, "| %s | %d |\n", a, counts[a])
	}
	fmt.Fprintf(&b, "\n| Operation | Method | Path | Area | Phase | Access | Notes |\n|---|---|---|---|---|---|---|\n")
	for _, so := range spec {
		op := byID[so.ID]
		area, phase := "–", "–"
		if op.Access != mtxapi.AccessUnused {
			area, phase = op.Area, fmt.Sprint(op.Phase)
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s | %s | %s |\n", so.ID, so.Method, so.Path, cell(area), phase, op.Access, cell(op.Note))
	}
	return b.Bytes()
}

func renderConfig() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- GENERATED by `./dev gen` (sidecar/cmd/gendocs) from sidecar/internal/settings. Do not edit. -->\n\n")
	fmt.Fprintf(&b, "# Sidecar configuration\n\n")
	fmt.Fprintf(&b, "The sidecar reads these environment variables. `compose.yaml` sets the ones an install usually needs from `.env` (see `.env.example`); add any other to the `sidecar` service's `environment:` in a `compose.override.yaml` (README: Configuration), since an upgrade replaces `compose.yaml`. ")
	fmt.Fprintf(&b, "Invalid values stop it at startup with a message naming every problem. Secrets are never configured here: ")
	fmt.Fprintf(&b, "the sidecar generates them into `state/` on first start.\n\n")
	fmt.Fprintf(&b, "| Variable | Default | Description |\n|---|---|---|\n")
	for _, v := range settings.Vars {
		def := "`" + v.Default + "`"
		switch {
		case v.Required:
			def = "required"
		case v.Default == "":
			def = "not set"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", v.Name, def, cell(v.Description))
	}
	return b.Bytes()
}

func cell(s string) string {
	return strings.NewReplacer("|", `\|`, "\n", " ").Replace(s)
}
